name = "CADETJulia"
uuid = "ddfd9fc4-ef49-4d31-a4ad-127c49fbcbce"
version = "0.1.0"
authors = ["Jesper Frandsen, Jan M. Breuer, Johannes Schm√∂lder"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqBDF = "6ad6398a-0878-4a85-9266-38940aa047c8"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ADTypes = "1.16.0"
Aqua = "0.8.13"
CSV = "0.10.15"
DataFrames = "1.7.0"
DataStructures = "0.18.22, 0.19"
HDF5 = "0.17.2"
LinearAlgebra = "1.10.0"
OrdinaryDiffEqBDF = "1.7.0"
Pkg = "1.10"
Plots = "1.40.17"
Reexport = "1.2.2"
SafeTestsets = "0.1.0"
SciMLBase = "2.106.0"
SparseArrays = "1.10"
SpecialFunctions = "2.5.1"
Sundials = "4.28.0"
Test = "1.10"
UnPack = "1.0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test", "SafeTestsets", "Aqua", "CSV", "DataFrames", "Plots"]
